services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # El backend no expone puertos al host, protegiendo el acceso directo.
    # Solo es accesible internamente a través de la red del compose.
    networks:
      - poke_network
    env_file:
      - .env
    volumes:
      # Volumen persistente para almacenar las posiciones y configuraciones del campo de batalla.
      # Docker poblará este volumen con las imágenes iniciales y el positions.json en el primer arranque.
      - battlefield_data:/app/Assets/Battlefields
    depends_on:
      db-poke:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # Solo el frontend expone puertos de conexión al exterior (puerto 80).
    ports:
      - "8080:80"
    networks:
      - poke_network
    depends_on:
      - backend
    restart: unless-stopped

  db-poke:
    image: mysql:8.0
    container_name: db-poke
    networks:
      - poke_network
    volumes:
      - db_poke_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "R00tMySQL"
      MYSQL_DATABASE: "pkmn_cards_db"
      TZ: "America/Argentina/Buenos_Aires"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pR00tMySQL" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  battlefield_data:
  db_poke_data:

networks:
  poke_network:
    driver: bridge
